dist: bionic
language: rust
sudo: required
addons:
    apt:
        packages:
            - python3-setuptools
            - python3-pip
env:
    global:
        - LIBRARY_PATH=/usr/local/lib
        - LD_LIBRARY_PATH=/usr/local/lib
        - LD_RUN_PATH=/usr/local/lib
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
script:
    - ./travis.sh
